stages:
  - build
  - deploy

# Define the build job
build:
  image: node:18
  stage: build
  script:
    - git clone https://github.com/ShardulTiurwadkar/LandingPage-DevOpSha-.git # Clone the GitHub repo
    - cd LandingPage-DevOpSha-                            # Navigate into the project directory
    - npm install                                         # Install dependencies
    - npm run grunt                                       # Run Grunt build task

# Define the deploy job
deploy:
  image: node:18
  stage: deploy
  script:
    - cd LandingPage-DevOpSha-                            # Navigate into the project directory
    - npm install -g vercel                              # Install Vercel CLI globally
    - vercel login --token $VERCEL_TOKEN                  # Login to Vercel using the token stored in GitLab CI/CD variable
    - vercel --prod                                       # Deploy to production on Vercel

# Optional: Cache node_modules between builds for faster CI
cache:
  paths:
    - node_modules/

